name: "Build"
on:
  pull_request:
  push:
jobs:
  release:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.4.0
      #    - uses: cachix/install-nix-action@v15
      #    - uses: cachix/cachix-action@v10
      #      with:
      #        name: ropfuscator
      #        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
